configName: wbz451_curiosity
folderName: wbz451_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\h3
processor: WBZ451
projectName: clock_config_wbz451_curiosity
settings:
  PackageFilter: bootloader;bsp;cec173x_soteria_lib;core;crypto;csp;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CX-BZ_DFP\1.0.105\WBZ451\atdf\WBZ451.atdf
