format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_PIN_10_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_11_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_12_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_13_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_14_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_15_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_16_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SERCOM2_PAD0}
  - type: String
    attributes: {id: BSP_PIN_16_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_17_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SERCOM2_PAD1}
  - type: String
    attributes: {id: BSP_PIN_17_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_40_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_41_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_42_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_43_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_44_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_47_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_4_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_5_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_6_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_7_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_9_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: Hex
    attributes: {id: CFGPCLKGEN1_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '589824'}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Combo
    attributes: {id: CONFIG_POSCMOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: HS}
  - type: Menu
    attributes: {id: CoreIARMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: CoreKEILMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: DEVICE_TCM_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: DSWDT_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32000'}
  - type: String
    attributes: {id: DSWDT_TIMEOUT_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 1.0 ms}
  - type: Boolean
    attributes: {id: FLASH_CONTROL_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvm, value: 'true'}
  - type: Boolean
    attributes: {id: FLASH_CONTROL_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: FLASH_CONTROL_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvm, value: NVM_InterruptHandler}
  - type: Boolean
    attributes: {id: FLASH_CONTROL_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvm, value: 'true'}
  - type: Boolean
    attributes: {id: GCLK_ID_4_CHEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: GCLK_ID_4_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: KeyValueSet
    attributes: {id: GCLK_ID_4_GENSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Integer
    attributes: {id: LPCLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32000'}
  - type: Boolean
    attributes: {id: NVIC_14_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: NVIC_14_0_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SERCOM2_I2C_InterruptHandler}
  - type: Boolean
    attributes: {id: NVIC_14_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: NVIC_3_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: NVIC_3_0_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: NVM_InterruptHandler}
  - type: Boolean
    attributes: {id: NVIC_3_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Hex
    attributes: {id: PMD3_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32763'}
  - type: Integer
    attributes: {id: POSC_OUT_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '16000000'}
  - type: Integer
    attributes: {id: RTC_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32000'}
  - type: Boolean
    attributes: {id: SERCOM2_CORE_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom2, value: 'true'}
  - type: Integer
    attributes: {id: SERCOM2_CORE_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: Boolean
    attributes: {id: SERCOM2_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom2, value: 'true'}
  - type: Boolean
    attributes: {id: SERCOM2_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: SERCOM2_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom2, value: SERCOM2_I2C_InterruptHandler}
  - type: Boolean
    attributes: {id: SERCOM2_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom2, value: 'true'}
  - type: Integer
    attributes: {id: SERCOM_SLOW_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32000'}
  - type: Integer
    attributes: {id: SPLL1_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: Integer
    attributes: {id: SPLL2_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Integer
    attributes: {id: SPLL3_RFPLL_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '96000000'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_FUNCTION_0}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: QSPI_SCK (out), value: '23', key: QSPI_SCK (out)}
          - type: Pair
            attributes: {description: SERCOM3_PAD0 (out), value: '10', key: SERCOM3_PAD0
                (out)}
          - type: Pair
            attributes: {description: SERCOM0_PAD0 (out), value: '3', key: SERCOM0_PAD0
                (out)}
          - type: Pair
            attributes: {description: TC1_WO1 (out), value: '20', key: TC1_WO1 (out)}
          - type: Pair
            attributes: {description: TC2_WO0 (out), value: '21', key: TC2_WO0 (out)}
          - type: Pair
            attributes: {description: SERCOM2_PAD2 (out), value: '7', key: SERCOM2_PAD2
                (out)}
          - type: Pair
            attributes: {description: SERCOM0_PAD3 (out), value: '3', key: SERCOM0_PAD3
                (out)}
          - type: Pair
            attributes: {description: TC3_WO0 (out), value: '22', key: TC3_WO0 (out)}
          - type: Pair
            attributes: {description: SERCOM1_PAD1 (out), value: '5', key: SERCOM1_PAD1
                (out)}
          - type: Pair
            attributes: {description: TC2_WO1 (out), value: '21', key: TC2_WO1 (out)}
          - type: Pair
            attributes: {description: QSPI_DATA2 (out), value: '25', key: QSPI_DATA2
                (out)}
          - type: Pair
            attributes: {description: SERCOM1_PAD0 (out), value: '6', key: SERCOM1_PAD0
                (out)}
          - type: Pair
            attributes: {description: SERCOM3_PAD3 (out), value: '9', key: SERCOM3_PAD3
                (out)}
          - type: Pair
            attributes: {description: SERCOM0_PAD1 (out), value: '2', key: SERCOM0_PAD1
                (out)}
          - type: Pair
            attributes: {description: SERCOM2_PAD0 (out), value: '8', key: SERCOM2_PAD0
                (out)}
          - type: Pair
            attributes: {description: SERCOM2_PAD3 (out), value: '7', key: SERCOM2_PAD3
                (out)}
          - type: Pair
            attributes: {description: TCC1_WO1, value: '15', key: TCC1_WO1}
          - type: Pair
            attributes: {description: TCC1_WO0, value: '15', key: TCC1_WO0}
          - type: Pair
            attributes: {description: QSPI_DATA3 (out), value: '27', key: QSPI_DATA3
                (out)}
          - type: Pair
            attributes: {description: QSPI_CS (out), value: '24', key: QSPI_CS (out)}
          - type: Pair
            attributes: {description: SERCOM1_PAD3 (out), value: '6', key: SERCOM1_PAD3
                (out)}
          - type: Pair
            attributes: {description: TCC1_WO5, value: '16', key: TCC1_WO5}
          - type: Pair
            attributes: {description: TCC1_WO4, value: '16', key: TCC1_WO4}
          - type: Pair
            attributes: {description: TCC1_WO3, value: '14', key: TCC1_WO3}
          - type: Pair
            attributes: {description: TCC1_WO2, value: '14', key: TCC1_WO2}
          - type: Pair
            attributes: {description: TCC0_WO4, value: '13', key: TCC0_WO4}
          - type: Pair
            attributes: {description: TCC0_WO3, value: '11', key: TCC0_WO3}
          - type: Pair
            attributes: {description: SERCOM2_PAD1 (out), value: '7', key: SERCOM2_PAD1
                (out)}
          - type: Pair
            attributes: {description: TCC0_WO5, value: '13', key: TCC0_WO5}
          - type: Pair
            attributes: {description: QSPI_DATA0 (out), value: '27', key: QSPI_DATA0
                (out)}
          - type: Pair
            attributes: {description: REFO3, value: '19', key: REFO3}
          - type: Pair
            attributes: {description: REFO2, value: '19', key: REFO2}
          - type: Pair
            attributes: {description: REFO1, value: '19', key: REFO1}
          - type: Pair
            attributes: {description: TC0_WO0 (out), value: '18', key: TC0_WO0 (out)}
          - type: Pair
            attributes: {description: SERCOM3_PAD2 (out), value: '10', key: SERCOM3_PAD2
                (out)}
          - type: Pair
            attributes: {description: REFO4, value: '19', key: REFO4}
          - type: Pair
            attributes: {description: TCC0_WO0, value: '12', key: TCC0_WO0}
          - type: Pair
            attributes: {description: TCC0_WO2, value: '11', key: TCC0_WO2}
          - type: Pair
            attributes: {description: TCC0_WO1, value: '12', key: TCC0_WO1}
          - type: Pair
            attributes: {description: SERCOM3_PAD1 (out), value: '10', key: SERCOM3_PAD1
                (out)}
          - type: Pair
            attributes: {description: SERCOM1_PAD2 (out), value: '4', key: SERCOM1_PAD2
                (out)}
          - type: Pair
            attributes: {description: TC1_WO0 (out), value: '20', key: TC1_WO0 (out)}
          - type: Pair
            attributes: {description: TC0_WO1 (out), value: '18', key: TC0_WO1 (out)}
          - type: Pair
            attributes: {description: TCC2_WO0, value: '17', key: TCC2_WO0}
          - type: Pair
            attributes: {description: SERCOM0_PAD2 (out), value: '1', key: SERCOM0_PAD2
                (out)}
          - type: Pair
            attributes: {description: CCL_OUT0, value: '28', key: CCL_OUT0}
          - type: Pair
            attributes: {description: CCL_OUT1, value: '28', key: CCL_OUT1}
          - type: Pair
            attributes: {description: QSPI_DATA1 (out), value: '26', key: QSPI_DATA1
                (out)}
          - type: Pair
            attributes: {description: TCC2_WO1, value: '17', key: TCC2_WO1}
          - type: Pair
            attributes: {description: TC3_WO1 (out), value: '22', key: TC3_WO1 (out)}
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_PIN_0}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: RPB2G4R, value: RPB2G4R, key: RPB2}
          - type: Pair
            attributes: {description: RPB3G4R, value: RPB3G4R, key: RPB3}
          - type: Pair
            attributes: {description: RPA10G4R, value: RPA10G4R, key: RPA10}
          - type: Pair
            attributes: {description: RPB0G2R, value: RPB0G2R, key: RPB0}
          - type: Pair
            attributes: {description: RPB1G3R, value: RPB1G3R, key: RPB1}
          - type: Pair
            attributes: {description: RPB10G4R, value: RPB10G4R, key: RPB10}
          - type: Pair
            attributes: {description: RPB11G4R, value: RPB11G4R, key: RPB11}
          - type: Pair
            attributes: {description: RPB12G2R, value: RPB12G2R, key: RPB12}
          - type: Pair
            attributes: {description: RPA13G4R, value: RPA13G3R, key: RPA13}
          - type: Pair
            attributes: {description: RPA14G4R, value: RPA14G4R, key: RPA14}
          - type: Pair
            attributes: {description: RPB13G3R, value: RPB13G3R, key: RPB13}
          - type: Pair
            attributes: {description: RPB8G2R, value: RPB8G2R, key: RPB8}
          - type: Pair
            attributes: {description: RPB9G3R, value: RPB9G3R, key: RPB9}
          - type: Pair
            attributes: {description: RPB6G4R, value: RPB6G4R, key: RPB6}
          - type: Pair
            attributes: {description: RPB7G4R, value: RPB7G4R, key: RPB7}
          - type: Pair
            attributes: {description: RPB4G2R, value: RPB4G2R, key: RPB4}
          - type: Pair
            attributes: {description: RPB5G3R, value: RPB5G3R, key: RPB5}
          - type: Pair
            attributes: {description: RPA1G4R, value: RPA1G4R, key: RPA1}
          - type: Pair
            attributes: {description: RPA2G4R, value: RPA2G4R, key: RPA2}
          - type: Pair
            attributes: {description: RPA0G3R, value: RPA0G3R, key: RPA0}
          - type: Pair
            attributes: {description: RPA9G4R, value: RPA9G4R, key: RPA9}
          - type: Pair
            attributes: {description: RPA7G2R, value: RPA7G2R, key: RPA7}
          - type: Pair
            attributes: {description: RPA8G4R, value: RPA8G4R, key: RPA8}
          - type: Pair
            attributes: {description: RPA5G4R, value: RPA5G4R, key: RPA5}
          - type: Pair
            attributes: {description: RPA6G4R, value: RPA6G4R, key: RPA6}
          - type: Pair
            attributes: {description: RPA3G3R, value: RPA3G3R, key: RPA3}
          - type: Pair
            attributes: {description: RPA4G4R, value: RPA4G4R, key: RPA4}
    - type: Values
      children:
      - type: User
        attributes: {value: '8'}
  - type: Boolean
    attributes: {id: USE_PPS_OUTPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '360', y: '20', id: core}
